/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddOn { 'name' : string, 'pricePerPerson' : bigint }
export interface AnnouncementPublic {
  'id' : string,
  'text' : string,
  'isActive' : boolean,
}
export interface BatchAvailability {
  'isSoldOut' : boolean,
  'batchId' : bigint,
  'seatsAvailable' : bigint,
}
export interface BatchCreateInput {
  'status' : string,
  'maxSeats' : bigint,
  'endDate' : string,
  'meetingPoint' : string,
  'guideId' : [] | [string],
  'pricePerPerson' : bigint,
  'guideName' : [] | [string],
  'trekName' : string,
  'trekSlug' : string,
  'startDate' : string,
}
export interface BatchPublic {
  'id' : bigint,
  'status' : BatchStatus,
  'endDate' : string,
  'guideId' : string,
  'pricePerPerson' : bigint,
  'totalSeats' : bigint,
  'bookedSeats' : bigint,
  'isSoldOut' : boolean,
  'trekSlug' : Slug,
  'seatsAvailable' : bigint,
  'startDate' : string,
}
export type BatchStatus = { 'Full' : null } |
  { 'Open' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export interface BatchUpdateInput {
  'status' : [] | [string],
  'maxSeats' : [] | [bigint],
  'endDate' : [] | [string],
  'meetingPoint' : [] | [string],
  'guideId' : [] | [string],
  'pricePerPerson' : [] | [bigint],
  'guideName' : [] | [string],
  'trekName' : [] | [string],
  'trekSlug' : [] | [string],
  'startDate' : [] | [string],
}
export type BlogCategory = { 'Stories' : null } |
  { 'Gear' : null } |
  { 'TrekTips' : null } |
  { 'YatraGuides' : null };
export interface BlogPostPublic {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'views' : bigint,
  'slug' : Slug,
  'tags' : Array<string>,
  'publishedAt' : Timestamp,
  'author' : string,
  'readTime' : bigint,
  'heroImage' : string,
  'excerpt' : string,
  'category' : BlogCategory,
}
export interface BookingPublic {
  'id' : bigint,
  'paymentStatus' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'travelers' : Array<TravelerInfo>,
  'totalAmount' : bigint,
  'addOns' : Array<AddOn>,
  'trekSlug' : Slug,
  'batchId' : bigint,
  'stripeSessionId' : [] | [string],
}
export interface CorporateLead {
  'id' : bigint,
  'contactName' : string,
  'createdAt' : Timestamp,
  'headcount' : bigint,
  'email' : string,
  'preferredDates' : string,
  'message' : string,
  'preferredTrek' : string,
  'companyName' : string,
  'phone' : string,
}
export type Difficulty = { 'Easy' : null } |
  { 'Extreme' : null } |
  { 'Difficult' : null } |
  { 'Moderate' : null };
export interface FaqVotesPublic { 'notHelpful' : bigint, 'helpful' : bigint }
export type GuideAvailability = { 'Available' : null } |
  { 'OnTrek' : null } |
  { 'OnLeave' : null };
export interface GuidePublic {
  'id' : string,
  'bio' : string,
  'currentAssignment' : [] | [string],
  'yearsExperience' : bigint,
  'name' : string,
  'designation' : string,
  'favoriteTrek' : string,
  'availability' : GuideAvailability,
  'rating' : number,
  'photo' : string,
  'certifications' : Array<string>,
  'totalTreksLed' : bigint,
}
export type LoyaltyTier = { 'SummitMaster' : null } |
  { 'Explorer' : null } |
  { 'Trailblazer' : null };
export type MealPreference = { 'Veg' : null } |
  { 'NonVeg' : null };
export type NewsletterPreference = { 'BlogPosts' : null } |
  { 'Offers' : null } |
  { 'WeatherAlerts' : null } |
  { 'NewBatches' : null };
export type PaymentStatus = { 'Paid' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface ReviewPublic {
  'id' : bigint,
  'userCity' : string,
  'userName' : string,
  'foodRating' : bigint,
  'verified' : boolean,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'reviewText' : string,
  'trekSlug' : Slug,
  'safetyRating' : bigint,
  'rating' : bigint,
  'helpfulVotes' : bigint,
  'guideRating' : bigint,
}
export type Slug = string;
export type Timestamp = bigint;
export interface TravelerInfo {
  'age' : bigint,
  'mealPreference' : MealPreference,
  'name' : string,
  'medicalConditions' : string,
  'emergencyContact' : string,
  'gender' : string,
  'tshirtSize' : string,
}
export interface Trek {
  'id' : bigint,
  'region' : string,
  'durationDays' : bigint,
  'startingPoint' : string,
  'tagline' : string,
  'durationNights' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'bestTime' : string,
  'slug' : Slug,
  'heroImage' : string,
  'nearestAirport' : string,
  'trekDistance' : bigint,
  'shortDescription' : string,
  'isFeatured' : boolean,
  'maxAltitude' : bigint,
  'basePrice' : bigint,
  'nearestRailhead' : string,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'principal' : UserId,
  'referralCode' : string,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'phone' : string,
  'wishlist' : Array<Slug>,
  'referralCredits' : bigint,
  'loyaltyTier' : LoyaltyTier,
  'totalTreksCompleted' : bigint,
}
export interface WaitlistEntryPublic {
  'id' : string,
  'status' : WaitlistStatus,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'notifiedAt' : [] | [bigint],
  'batchId' : string,
  'phone' : string,
  'position' : bigint,
  'numPeople' : bigint,
}
export type WaitlistResult = {
    'ok' : { 'waitlistId' : string, 'position' : bigint }
  } |
  { 'err' : string };
export type WaitlistStatus = { 'Notified' : null } |
  { 'Booked' : null } |
  { 'Waiting' : null } |
  { 'Expired' : null };
export interface Yatra {
  'id' : bigint,
  'durationDays' : bigint,
  'tagline' : string,
  'name' : string,
  'slug' : Slug,
  'heroImage' : string,
  'shortDescription' : string,
  'category' : string,
  'basePrice' : bigint,
  'nextDeparture' : string,
}
export interface _SERVICE {
  'addToWishlist' : ActorMethod<[string], boolean>,
  'assignGuideToBatch' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'calculateGroupPrice' : ActorMethod<
    [string, bigint, Array<AddOn>, bigint],
    bigint
  >,
  'cancelBooking' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'confirmBookingPayment' : ActorMethod<
    [bigint, string],
    { 'ok' : BookingPublic } |
      { 'err' : string }
  >,
  'createAnnouncement' : ActorMethod<[string], AnnouncementPublic>,
  'createBatch' : ActorMethod<
    [BatchCreateInput],
    { 'ok' : BatchPublic } |
      { 'err' : string }
  >,
  'createBooking' : ActorMethod<
    [bigint, bigint, Array<AddOn>, Array<TravelerInfo>, boolean],
    {
        'ok' : {
          'bookingId' : bigint,
          'checkoutUrl' : string,
          'sessionId' : string,
        }
      } |
      { 'err' : string }
  >,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, string, string],
    UserProfilePublic
  >,
  'deleteAnnouncement' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBatch' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getActiveAnnouncements' : ActorMethod<[], Array<AnnouncementPublic>>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getAllAnnouncements' : ActorMethod<[], Array<AnnouncementPublic>>,
  'getAllGuides' : ActorMethod<[], Array<GuidePublic>>,
  'getAllTreks' : ActorMethod<[], Array<Trek>>,
  'getAllYatras' : ActorMethod<[], Array<Yatra>>,
  'getAvailability' : ActorMethod<
    [bigint],
    {
      'total' : bigint,
      'reserved' : bigint,
      'available' : bigint,
      'soldOut' : boolean,
      'percentFilled' : bigint,
    }
  >,
  'getAvailableBatches' : ActorMethod<[], Array<BatchPublic>>,
  'getAverageRating' : ActorMethod<[string], bigint>,
  'getBatchAvailability' : ActorMethod<[bigint], [] | [BatchAvailability]>,
  'getBatchById' : ActorMethod<[bigint], [] | [BatchPublic]>,
  'getBatchesAll' : ActorMethod<[], Array<BatchPublic>>,
  'getBatchesByTrek' : ActorMethod<[string], Array<BatchPublic>>,
  'getBlogByCategory' : ActorMethod<[BlogCategory], Array<BlogPostPublic>>,
  'getBlogBySlug' : ActorMethod<[string], [] | [BlogPostPublic]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPostPublic>>,
  'getBookingById' : ActorMethod<[bigint], [] | [BookingPublic]>,
  'getBookingsByUser' : ActorMethod<[], Array<BookingPublic>>,
  'getCorporateLeads' : ActorMethod<[], Array<CorporateLead>>,
  'getFaqVotes' : ActorMethod<[string, bigint], FaqVotesPublic>,
  'getFeaturedTreks' : ActorMethod<[], Array<Trek>>,
  'getGuideById' : ActorMethod<[string], [] | [GuidePublic]>,
  'getReviewsByTrek' : ActorMethod<[string], Array<ReviewPublic>>,
  'getStripePublicKey' : ActorMethod<[], string>,
  'getSubscriberCount' : ActorMethod<[], bigint>,
  'getTrekBySlug' : ActorMethod<[string], [] | [Trek]>,
  'getTreksByDifficulty' : ActorMethod<[Difficulty], Array<Trek>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getWaitlistByBatch' : ActorMethod<[string], Array<WaitlistEntryPublic>>,
  'getWaitlistPosition' : ActorMethod<[string, string], [] | [bigint]>,
  'getYatraBySlug' : ActorMethod<[string], [] | [Yatra]>,
  'incrementBlogViews' : ActorMethod<[string], boolean>,
  'initAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'joinWaitlist' : ActorMethod<
    [string, string, string, string, bigint],
    WaitlistResult
  >,
  'notifyNextOnWaitlist' : ActorMethod<[string], boolean>,
  'promoteFromWaitlist' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeFromWishlist' : ActorMethod<[string], boolean>,
  'sendManualWaitlistNotification' : ActorMethod<
    [string, string, string],
    boolean
  >,
  'setStripeSecretKey' : ActorMethod<[string, string], undefined>,
  'submitCorporateLead' : ActorMethod<
    [string, string, string, string, bigint, string, string, string],
    CorporateLead
  >,
  'submitReview' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, bigint, string],
    ReviewPublic
  >,
  'subscribe' : ActorMethod<[string, Array<NewsletterPreference>], boolean>,
  'unsubscribe' : ActorMethod<[string], boolean>,
  'updateAnnouncement' : ActorMethod<
    [string, string, boolean],
    { 'ok' : AnnouncementPublic } |
      { 'err' : string }
  >,
  'updateBatch' : ActorMethod<
    [bigint, BatchUpdateInput],
    { 'ok' : BatchPublic } |
      { 'err' : string }
  >,
  'updateGuideAvailability' : ActorMethod<
    [string, GuideAvailability],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateGuidePhoto' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], boolean>,
  'upsertGuide' : ActorMethod<
    [GuidePublic],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'voteFaq' : ActorMethod<[string, bigint, boolean], boolean>,
  'voteHelpful' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];