/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddOn = IDL.Record({
  'name' : IDL.Text,
  'pricePerPerson' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const MealPreference = IDL.Variant({
  'Veg' : IDL.Null,
  'NonVeg' : IDL.Null,
});
export const TravelerInfo = IDL.Record({
  'age' : IDL.Nat,
  'mealPreference' : MealPreference,
  'name' : IDL.Text,
  'medicalConditions' : IDL.Text,
  'emergencyContact' : IDL.Text,
  'gender' : IDL.Text,
  'tshirtSize' : IDL.Text,
});
export const Slug = IDL.Text;
export const BookingPublic = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'travelers' : IDL.Vec(TravelerInfo),
  'totalAmount' : IDL.Nat,
  'addOns' : IDL.Vec(AddOn),
  'trekSlug' : Slug,
  'batchId' : IDL.Nat,
  'stripeSessionId' : IDL.Opt(IDL.Text),
});
export const LoyaltyTier = IDL.Variant({
  'SummitMaster' : IDL.Null,
  'Explorer' : IDL.Null,
  'Trailblazer' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'principal' : UserId,
  'referralCode' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'wishlist' : IDL.Vec(Slug),
  'referralCredits' : IDL.Nat,
  'loyaltyTier' : LoyaltyTier,
  'totalTreksCompleted' : IDL.Nat,
});
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Extreme' : IDL.Null,
  'Difficult' : IDL.Null,
  'Moderate' : IDL.Null,
});
export const Trek = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'durationDays' : IDL.Nat,
  'startingPoint' : IDL.Text,
  'tagline' : IDL.Text,
  'durationNights' : IDL.Nat,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'bestTime' : IDL.Text,
  'slug' : Slug,
  'heroImage' : IDL.Text,
  'nearestAirport' : IDL.Text,
  'trekDistance' : IDL.Nat,
  'shortDescription' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'maxAltitude' : IDL.Nat,
  'basePrice' : IDL.Nat,
  'nearestRailhead' : IDL.Text,
});
export const Yatra = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'slug' : Slug,
  'heroImage' : IDL.Text,
  'shortDescription' : IDL.Text,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
  'nextDeparture' : IDL.Text,
});
export const BatchStatus = IDL.Variant({
  'Full' : IDL.Null,
  'Open' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const BatchPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : BatchStatus,
  'endDate' : IDL.Text,
  'guideId' : IDL.Text,
  'pricePerPerson' : IDL.Nat,
  'totalSeats' : IDL.Nat,
  'bookedSeats' : IDL.Nat,
  'isSoldOut' : IDL.Bool,
  'trekSlug' : Slug,
  'seatsAvailable' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const BatchAvailability = IDL.Record({
  'isSoldOut' : IDL.Bool,
  'batchId' : IDL.Nat,
  'seatsAvailable' : IDL.Nat,
});
export const BlogCategory = IDL.Variant({
  'Stories' : IDL.Null,
  'Gear' : IDL.Null,
  'TrekTips' : IDL.Null,
  'YatraGuides' : IDL.Null,
});
export const BlogPostPublic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'views' : IDL.Nat,
  'slug' : Slug,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Timestamp,
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'heroImage' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : BlogCategory,
});
export const CorporateLead = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'createdAt' : Timestamp,
  'headcount' : IDL.Nat,
  'email' : IDL.Text,
  'preferredDates' : IDL.Text,
  'message' : IDL.Text,
  'preferredTrek' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const FaqVotesPublic = IDL.Record({
  'notHelpful' : IDL.Nat,
  'helpful' : IDL.Nat,
});
export const ReviewPublic = IDL.Record({
  'id' : IDL.Nat,
  'userCity' : IDL.Text,
  'userName' : IDL.Text,
  'foodRating' : IDL.Nat,
  'verified' : IDL.Bool,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'reviewText' : IDL.Text,
  'trekSlug' : Slug,
  'safetyRating' : IDL.Nat,
  'rating' : IDL.Nat,
  'helpfulVotes' : IDL.Nat,
  'guideRating' : IDL.Nat,
});
export const NewsletterPreference = IDL.Variant({
  'BlogPosts' : IDL.Null,
  'Offers' : IDL.Null,
  'WeatherAlerts' : IDL.Null,
  'NewBatches' : IDL.Null,
});

export const idlService = IDL.Service({
  'addToWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'calculateGroupPrice' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(AddOn), IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'cancelBooking' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'confirmBookingPayment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : BookingPublic, 'err' : IDL.Text })],
      [],
    ),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(AddOn), IDL.Vec(TravelerInfo), IDL.Bool],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'bookingId' : IDL.Nat,
            'checkoutUrl' : IDL.Text,
            'sessionId' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UserProfilePublic],
      [],
    ),
  'getAllTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'getAllYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
  'getAvailability' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'reserved' : IDL.Nat,
          'available' : IDL.Nat,
          'soldOut' : IDL.Bool,
          'percentFilled' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAvailableBatches' : IDL.Func([], [IDL.Vec(BatchPublic)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getBatchAvailability' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BatchAvailability)],
      ['query'],
    ),
  'getBatchById' : IDL.Func([IDL.Nat], [IDL.Opt(BatchPublic)], ['query']),
  'getBatchesByTrek' : IDL.Func([IDL.Text], [IDL.Vec(BatchPublic)], ['query']),
  'getBlogByCategory' : IDL.Func(
      [BlogCategory],
      [IDL.Vec(BlogPostPublic)],
      ['query'],
    ),
  'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPostPublic)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPostPublic)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(BookingPublic)], ['query']),
  'getBookingsByUser' : IDL.Func([], [IDL.Vec(BookingPublic)], ['query']),
  'getCorporateLeads' : IDL.Func([], [IDL.Vec(CorporateLead)], []),
  'getFaqVotes' : IDL.Func([IDL.Text, IDL.Nat], [FaqVotesPublic], ['query']),
  'getFeaturedTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'getReviewsByTrek' : IDL.Func([IDL.Text], [IDL.Vec(ReviewPublic)], ['query']),
  'getStripePublicKey' : IDL.Func([], [IDL.Text], ['query']),
  'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
  'getTreksByDifficulty' : IDL.Func([Difficulty], [IDL.Vec(Trek)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getYatraBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
  'incrementBlogViews' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setStripeSecretKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitCorporateLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [CorporateLead],
      [],
    ),
  'submitReview' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [ReviewPublic],
      [],
    ),
  'subscribe' : IDL.Func(
      [IDL.Text, IDL.Vec(NewsletterPreference)],
      [IDL.Bool],
      [],
    ),
  'unsubscribe' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [IDL.Bool], []),
  'voteFaq' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'voteHelpful' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddOn = IDL.Record({ 'name' : IDL.Text, 'pricePerPerson' : IDL.Nat });
  const PaymentStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const MealPreference = IDL.Variant({ 'Veg' : IDL.Null, 'NonVeg' : IDL.Null });
  const TravelerInfo = IDL.Record({
    'age' : IDL.Nat,
    'mealPreference' : MealPreference,
    'name' : IDL.Text,
    'medicalConditions' : IDL.Text,
    'emergencyContact' : IDL.Text,
    'gender' : IDL.Text,
    'tshirtSize' : IDL.Text,
  });
  const Slug = IDL.Text;
  const BookingPublic = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'travelers' : IDL.Vec(TravelerInfo),
    'totalAmount' : IDL.Nat,
    'addOns' : IDL.Vec(AddOn),
    'trekSlug' : Slug,
    'batchId' : IDL.Nat,
    'stripeSessionId' : IDL.Opt(IDL.Text),
  });
  const LoyaltyTier = IDL.Variant({
    'SummitMaster' : IDL.Null,
    'Explorer' : IDL.Null,
    'Trailblazer' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'principal' : UserId,
    'referralCode' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'wishlist' : IDL.Vec(Slug),
    'referralCredits' : IDL.Nat,
    'loyaltyTier' : LoyaltyTier,
    'totalTreksCompleted' : IDL.Nat,
  });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Extreme' : IDL.Null,
    'Difficult' : IDL.Null,
    'Moderate' : IDL.Null,
  });
  const Trek = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'durationDays' : IDL.Nat,
    'startingPoint' : IDL.Text,
    'tagline' : IDL.Text,
    'durationNights' : IDL.Nat,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'bestTime' : IDL.Text,
    'slug' : Slug,
    'heroImage' : IDL.Text,
    'nearestAirport' : IDL.Text,
    'trekDistance' : IDL.Nat,
    'shortDescription' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'maxAltitude' : IDL.Nat,
    'basePrice' : IDL.Nat,
    'nearestRailhead' : IDL.Text,
  });
  const Yatra = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'slug' : Slug,
    'heroImage' : IDL.Text,
    'shortDescription' : IDL.Text,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
    'nextDeparture' : IDL.Text,
  });
  const BatchStatus = IDL.Variant({
    'Full' : IDL.Null,
    'Open' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const BatchPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : BatchStatus,
    'endDate' : IDL.Text,
    'guideId' : IDL.Text,
    'pricePerPerson' : IDL.Nat,
    'totalSeats' : IDL.Nat,
    'bookedSeats' : IDL.Nat,
    'isSoldOut' : IDL.Bool,
    'trekSlug' : Slug,
    'seatsAvailable' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const BatchAvailability = IDL.Record({
    'isSoldOut' : IDL.Bool,
    'batchId' : IDL.Nat,
    'seatsAvailable' : IDL.Nat,
  });
  const BlogCategory = IDL.Variant({
    'Stories' : IDL.Null,
    'Gear' : IDL.Null,
    'TrekTips' : IDL.Null,
    'YatraGuides' : IDL.Null,
  });
  const BlogPostPublic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'views' : IDL.Nat,
    'slug' : Slug,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Timestamp,
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'heroImage' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : BlogCategory,
  });
  const CorporateLead = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'createdAt' : Timestamp,
    'headcount' : IDL.Nat,
    'email' : IDL.Text,
    'preferredDates' : IDL.Text,
    'message' : IDL.Text,
    'preferredTrek' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FaqVotesPublic = IDL.Record({
    'notHelpful' : IDL.Nat,
    'helpful' : IDL.Nat,
  });
  const ReviewPublic = IDL.Record({
    'id' : IDL.Nat,
    'userCity' : IDL.Text,
    'userName' : IDL.Text,
    'foodRating' : IDL.Nat,
    'verified' : IDL.Bool,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'reviewText' : IDL.Text,
    'trekSlug' : Slug,
    'safetyRating' : IDL.Nat,
    'rating' : IDL.Nat,
    'helpfulVotes' : IDL.Nat,
    'guideRating' : IDL.Nat,
  });
  const NewsletterPreference = IDL.Variant({
    'BlogPosts' : IDL.Null,
    'Offers' : IDL.Null,
    'WeatherAlerts' : IDL.Null,
    'NewBatches' : IDL.Null,
  });
  
  return IDL.Service({
    'addToWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'calculateGroupPrice' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(AddOn), IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'cancelBooking' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'confirmBookingPayment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : BookingPublic, 'err' : IDL.Text })],
        [],
      ),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(AddOn), IDL.Vec(TravelerInfo), IDL.Bool],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'bookingId' : IDL.Nat,
              'checkoutUrl' : IDL.Text,
              'sessionId' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UserProfilePublic],
        [],
      ),
    'getAllTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'getAllYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
    'getAvailability' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'reserved' : IDL.Nat,
            'available' : IDL.Nat,
            'soldOut' : IDL.Bool,
            'percentFilled' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAvailableBatches' : IDL.Func([], [IDL.Vec(BatchPublic)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getBatchAvailability' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BatchAvailability)],
        ['query'],
      ),
    'getBatchById' : IDL.Func([IDL.Nat], [IDL.Opt(BatchPublic)], ['query']),
    'getBatchesByTrek' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BatchPublic)],
        ['query'],
      ),
    'getBlogByCategory' : IDL.Func(
        [BlogCategory],
        [IDL.Vec(BlogPostPublic)],
        ['query'],
      ),
    'getBlogBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BlogPostPublic)],
        ['query'],
      ),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPostPublic)], ['query']),
    'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(BookingPublic)], ['query']),
    'getBookingsByUser' : IDL.Func([], [IDL.Vec(BookingPublic)], ['query']),
    'getCorporateLeads' : IDL.Func([], [IDL.Vec(CorporateLead)], []),
    'getFaqVotes' : IDL.Func([IDL.Text, IDL.Nat], [FaqVotesPublic], ['query']),
    'getFeaturedTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'getReviewsByTrek' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReviewPublic)],
        ['query'],
      ),
    'getStripePublicKey' : IDL.Func([], [IDL.Text], ['query']),
    'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
    'getTreksByDifficulty' : IDL.Func([Difficulty], [IDL.Vec(Trek)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getYatraBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
    'incrementBlogViews' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setStripeSecretKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitCorporateLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [CorporateLead],
        [],
      ),
    'submitReview' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [ReviewPublic],
        [],
      ),
    'subscribe' : IDL.Func(
        [IDL.Text, IDL.Vec(NewsletterPreference)],
        [IDL.Bool],
        [],
      ),
    'unsubscribe' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [IDL.Bool], []),
    'voteFaq' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'voteHelpful' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };