/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface BlogPostPublic {
    id: bigint;
    title: string;
    content: string;
    views: bigint;
    slug: Slug;
    tags: Array<string>;
    publishedAt: Timestamp;
    author: string;
    readTime: bigint;
    heroImage: string;
    excerpt: string;
    category: BlogCategory;
}
export interface AddOn {
    name: string;
    pricePerPerson: bigint;
}
export type Slug = string;
export interface FaqVotesPublic {
    notHelpful: bigint;
    helpful: bigint;
}
export interface Trek {
    id: bigint;
    region: string;
    durationDays: bigint;
    startingPoint: string;
    tagline: string;
    durationNights: bigint;
    difficulty: Difficulty;
    name: string;
    bestTime: string;
    slug: Slug;
    heroImage: string;
    nearestAirport: string;
    trekDistance: bigint;
    shortDescription: string;
    isFeatured: boolean;
    maxAltitude: bigint;
    basePrice: bigint;
    nearestRailhead: string;
}
export interface BatchAvailability {
    isSoldOut: boolean;
    batchId: bigint;
    seatsAvailable: bigint;
}
export interface CorporateLead {
    id: bigint;
    contactName: string;
    createdAt: Timestamp;
    headcount: bigint;
    email: string;
    preferredDates: string;
    message: string;
    preferredTrek: string;
    companyName: string;
    phone: string;
}
export interface GuidePublic {
    id: string;
    bio: string;
    currentAssignment?: string;
    yearsExperience: bigint;
    name: string;
    designation: string;
    favoriteTrek: string;
    availability: GuideAvailability;
    rating: number;
    photo: string;
    certifications: Array<string>;
    totalTreksLed: bigint;
}
export interface BatchUpdateInput {
    status?: string;
    maxSeats?: bigint;
    endDate?: string;
    meetingPoint?: string;
    guideId?: string;
    pricePerPerson?: bigint;
    guideName?: string;
    trekName?: string;
    trekSlug?: string;
    startDate?: string;
}
export interface BatchCreateInput {
    status: string;
    maxSeats: bigint;
    endDate: string;
    meetingPoint: string;
    guideId?: string;
    pricePerPerson: bigint;
    guideName?: string;
    trekName: string;
    trekSlug: string;
    startDate: string;
}
export interface AnnouncementPublic {
    id: string;
    text: string;
    isActive: boolean;
}
export interface WaitlistEntryPublic {
    id: string;
    status: WaitlistStatus;
    name: string;
    createdAt: bigint;
    email: string;
    notifiedAt?: bigint;
    batchId: string;
    phone: string;
    position: bigint;
    numPeople: bigint;
}
export interface BookingPublic {
    id: bigint;
    paymentStatus: PaymentStatus;
    userId: UserId;
    createdAt: Timestamp;
    travelers: Array<TravelerInfo>;
    totalAmount: bigint;
    addOns: Array<AddOn>;
    trekSlug: Slug;
    batchId: bigint;
    stripeSessionId?: string;
}
export interface ReviewPublic {
    id: bigint;
    userCity: string;
    userName: string;
    foodRating: bigint;
    verified: boolean;
    userId: UserId;
    createdAt: Timestamp;
    reviewText: string;
    trekSlug: Slug;
    safetyRating: bigint;
    rating: bigint;
    helpfulVotes: bigint;
    guideRating: bigint;
}
export interface UserProfilePublic {
    principal: UserId;
    referralCode: string;
    city: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    phone: string;
    wishlist: Array<Slug>;
    referralCredits: bigint;
    loyaltyTier: LoyaltyTier;
    totalTreksCompleted: bigint;
}
export type UserId = Principal;
export interface TravelerInfo {
    age: bigint;
    mealPreference: MealPreference;
    name: string;
    medicalConditions: string;
    emergencyContact: string;
    gender: string;
    tshirtSize: string;
}
export interface Yatra {
    id: bigint;
    durationDays: bigint;
    tagline: string;
    name: string;
    slug: Slug;
    heroImage: string;
    shortDescription: string;
    category: string;
    basePrice: bigint;
    nextDeparture: string;
}
export interface BatchPublic {
    id: bigint;
    status: BatchStatus;
    endDate: string;
    guideId: string;
    pricePerPerson: bigint;
    totalSeats: bigint;
    bookedSeats: bigint;
    isSoldOut: boolean;
    trekSlug: Slug;
    seatsAvailable: bigint;
    startDate: string;
}
export type WaitlistResult = {
    __kind__: "ok";
    ok: {
        waitlistId: string;
        position: bigint;
    };
} | {
    __kind__: "err";
    err: string;
};
export enum BatchStatus {
    Full = "Full",
    Open = "Open",
    Cancelled = "Cancelled",
    Completed = "Completed"
}
export enum BlogCategory {
    Stories = "Stories",
    Gear = "Gear",
    TrekTips = "TrekTips",
    YatraGuides = "YatraGuides"
}
export enum Difficulty {
    Easy = "Easy",
    Extreme = "Extreme",
    Difficult = "Difficult",
    Moderate = "Moderate"
}
export enum GuideAvailability {
    Available = "Available",
    OnTrek = "OnTrek",
    OnLeave = "OnLeave"
}
export enum LoyaltyTier {
    SummitMaster = "SummitMaster",
    Explorer = "Explorer",
    Trailblazer = "Trailblazer"
}
export enum MealPreference {
    Veg = "Veg",
    NonVeg = "NonVeg"
}
export enum NewsletterPreference {
    BlogPosts = "BlogPosts",
    Offers = "Offers",
    WeatherAlerts = "WeatherAlerts",
    NewBatches = "NewBatches"
}
export enum PaymentStatus {
    Paid = "Paid",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum WaitlistStatus {
    Notified = "Notified",
    Booked = "Booked",
    Waiting = "Waiting",
    Expired = "Expired"
}
export interface backendInterface {
    addToWishlist(slug: string): Promise<boolean>;
    assignGuideToBatch(batchId: string, guideId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    calculateGroupPrice(trekSlug: string, groupSize: bigint, addOns: Array<AddOn>, batchId: bigint): Promise<bigint>;
    cancelBooking(id: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    confirmBookingPayment(bookingId: bigint, stripeSessionId: string): Promise<{
        __kind__: "ok";
        ok: BookingPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createAnnouncement(text: string): Promise<AnnouncementPublic>;
    createBatch(input: BatchCreateInput): Promise<{
        __kind__: "ok";
        ok: BatchPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createBooking(batchId: bigint, groupSize: bigint, addOns: Array<AddOn>, travelers: Array<TravelerInfo>, applyEarlyBird: boolean): Promise<{
        __kind__: "ok";
        ok: {
            bookingId: bigint;
            checkoutUrl: string;
            sessionId: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    createOrUpdateProfile(name: string, email: string, phone: string, city: string): Promise<UserProfilePublic>;
    deleteAnnouncement(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteBatch(batchId: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveAnnouncements(): Promise<Array<AnnouncementPublic>>;
    getAdminPrincipal(): Promise<Principal | null>;
    getAllAnnouncements(): Promise<Array<AnnouncementPublic>>;
    getAllGuides(): Promise<Array<GuidePublic>>;
    getAllTreks(): Promise<Array<Trek>>;
    getAllYatras(): Promise<Array<Yatra>>;
    getAvailability(batchId: bigint): Promise<{
        total: bigint;
        reserved: bigint;
        available: bigint;
        soldOut: boolean;
        percentFilled: bigint;
    }>;
    getAvailableBatches(): Promise<Array<BatchPublic>>;
    getAverageRating(trekSlug: string): Promise<bigint>;
    getBatchAvailability(batchId: bigint): Promise<BatchAvailability | null>;
    getBatchById(id: bigint): Promise<BatchPublic | null>;
    getBatchesAll(): Promise<Array<BatchPublic>>;
    getBatchesByTrek(trekSlug: string): Promise<Array<BatchPublic>>;
    getBlogByCategory(category: BlogCategory): Promise<Array<BlogPostPublic>>;
    getBlogBySlug(slug: string): Promise<BlogPostPublic | null>;
    getBlogPosts(): Promise<Array<BlogPostPublic>>;
    getBookingById(id: bigint): Promise<BookingPublic | null>;
    getBookingsByUser(): Promise<Array<BookingPublic>>;
    getCorporateLeads(): Promise<Array<CorporateLead>>;
    getFaqVotes(trekSlug: string, faqIndex: bigint): Promise<FaqVotesPublic>;
    getFeaturedTreks(): Promise<Array<Trek>>;
    getGuideById(id: string): Promise<GuidePublic | null>;
    getReviewsByTrek(trekSlug: string): Promise<Array<ReviewPublic>>;
    getStripePublicKey(): Promise<string>;
    getSubscriberCount(): Promise<bigint>;
    getTrekBySlug(slug: string): Promise<Trek | null>;
    getTreksByDifficulty(difficulty: Difficulty): Promise<Array<Trek>>;
    getUserProfile(): Promise<UserProfilePublic | null>;
    getWaitlistByBatch(batchId: string): Promise<Array<WaitlistEntryPublic>>;
    getWaitlistPosition(batchId: string, email: string): Promise<bigint | null>;
    getYatraBySlug(slug: string): Promise<Yatra | null>;
    incrementBlogViews(slug: string): Promise<boolean>;
    initAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    joinWaitlist(batchId: string, name: string, email: string, phone: string, numPeople: bigint): Promise<WaitlistResult>;
    notifyNextOnWaitlist(batchId: string): Promise<boolean>;
    promoteFromWaitlist(batchId: string, waitlistId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeFromWishlist(slug: string): Promise<boolean>;
    sendManualWaitlistNotification(batchId: string, waitlistId: string, message: string): Promise<boolean>;
    setStripeSecretKey(secretKey: string, publicKey: string): Promise<void>;
    submitCorporateLead(companyName: string, contactName: string, email: string, phone: string, headcount: bigint, preferredDates: string, preferredTrek: string, message: string): Promise<CorporateLead>;
    submitReview(trekSlug: string, userName: string, userCity: string, rating: bigint, guideRating: bigint, foodRating: bigint, safetyRating: bigint, reviewText: string): Promise<ReviewPublic>;
    subscribe(email: string, preferences: Array<NewsletterPreference>): Promise<boolean>;
    unsubscribe(email: string): Promise<boolean>;
    updateAnnouncement(id: string, text: string, isActive: boolean): Promise<{
        __kind__: "ok";
        ok: AnnouncementPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateBatch(batchId: bigint, input: BatchUpdateInput): Promise<{
        __kind__: "ok";
        ok: BatchPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateGuideAvailability(guideId: string, availability: GuideAvailability): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateGuidePhoto(guideId: string, photoUrl: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updatePaymentStatus(id: bigint, status: PaymentStatus): Promise<boolean>;
    upsertGuide(guide: GuidePublic): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    voteFaq(trekSlug: string, faqIndex: bigint, isHelpful: boolean): Promise<boolean>;
    voteHelpful(reviewId: bigint): Promise<boolean>;
}
import type { AddOn as _AddOn, AnnouncementPublic as _AnnouncementPublic, BatchAvailability as _BatchAvailability, BatchCreateInput as _BatchCreateInput, BatchPublic as _BatchPublic, BatchStatus as _BatchStatus, BatchUpdateInput as _BatchUpdateInput, BlogCategory as _BlogCategory, BlogPostPublic as _BlogPostPublic, BookingPublic as _BookingPublic, Difficulty as _Difficulty, GuideAvailability as _GuideAvailability, GuidePublic as _GuidePublic, LoyaltyTier as _LoyaltyTier, MealPreference as _MealPreference, NewsletterPreference as _NewsletterPreference, PaymentStatus as _PaymentStatus, Slug as _Slug, Timestamp as _Timestamp, TravelerInfo as _TravelerInfo, Trek as _Trek, UserId as _UserId, UserProfilePublic as _UserProfilePublic, WaitlistEntryPublic as _WaitlistEntryPublic, WaitlistResult as _WaitlistResult, WaitlistStatus as _WaitlistStatus, Yatra as _Yatra } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWishlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async assignGuideToBatch(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.assignGuideToBatch(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignGuideToBatch(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async calculateGroupPrice(arg0: string, arg1: bigint, arg2: Array<AddOn>, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateGroupPrice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateGroupPrice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmBookingPayment(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: BookingPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBookingPayment(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBookingPayment(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAnnouncement(arg0: string): Promise<AnnouncementPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0);
            return result;
        }
    }
    async createBatch(arg0: BatchCreateInput): Promise<{
        __kind__: "ok";
        ok: BatchPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createBatch(to_candid_BatchCreateInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBatch(to_candid_BatchCreateInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: bigint, arg1: bigint, arg2: Array<AddOn>, arg3: Array<TravelerInfo>, arg4: boolean): Promise<{
        __kind__: "ok";
        ok: {
            bookingId: bigint;
            checkoutUrl: string;
            sessionId: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, arg3);
                return from_candid_UserProfilePublic_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, arg3);
            return from_candid_UserProfilePublic_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnnouncement(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBatch(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBatch(arg0);
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBatch(arg0);
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveAnnouncements(): Promise<Array<AnnouncementPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAnnouncements();
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnnouncements(): Promise<Array<AnnouncementPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result;
        }
    }
    async getAllGuides(): Promise<Array<GuidePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGuides();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGuides();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTreks(): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTreks();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTreks();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllYatras(): Promise<Array<Yatra>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllYatras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllYatras();
            return result;
        }
    }
    async getAvailability(arg0: bigint): Promise<{
        total: bigint;
        reserved: bigint;
        available: bigint;
        soldOut: boolean;
        percentFilled: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailability(arg0);
            return result;
        }
    }
    async getAvailableBatches(): Promise<Array<BatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBatches();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBatches();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageRating(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return result;
        }
    }
    async getBatchAvailability(arg0: bigint): Promise<BatchAvailability | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchAvailability(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchAvailability(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchById(arg0: bigint): Promise<BatchPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchById(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchById(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchesAll(): Promise<Array<BatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchesAll();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchesAll();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchesByTrek(arg0: string): Promise<Array<BatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchesByTrek(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchesByTrek(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogByCategory(arg0: BlogCategory): Promise<Array<BlogPostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogByCategory(to_candid_BlogCategory_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogByCategory(to_candid_BlogCategory_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogBySlug(arg0: string): Promise<BlogPostPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogBySlug(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogBySlug(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(): Promise<Array<BlogPostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: bigint): Promise<BookingPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByUser(): Promise<Array<BookingPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCorporateLeads(): Promise<Array<CorporateLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCorporateLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCorporateLeads();
            return result;
        }
    }
    async getFaqVotes(arg0: string, arg1: bigint): Promise<FaqVotesPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getFaqVotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFaqVotes(arg0, arg1);
            return result;
        }
    }
    async getFeaturedTreks(): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedTreks();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedTreks();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuideById(arg0: string): Promise<GuidePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuideById(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuideById(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByTrek(arg0: string): Promise<Array<ReviewPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByTrek(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByTrek(arg0);
            return result;
        }
    }
    async getStripePublicKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripePublicKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripePublicKey();
            return result;
        }
    }
    async getSubscriberCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriberCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriberCount();
            return result;
        }
    }
    async getTrekBySlug(arg0: string): Promise<Trek | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrekBySlug(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrekBySlug(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreksByDifficulty(arg0: Difficulty): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreksByDifficulty(to_candid_Difficulty_n58(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreksByDifficulty(to_candid_Difficulty_n58(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaitlistByBatch(arg0: string): Promise<Array<WaitlistEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitlistByBatch(arg0);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitlistByBatch(arg0);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaitlistPosition(arg0: string, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitlistPosition(arg0, arg1);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitlistPosition(arg0, arg1);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYatraBySlug(arg0: string): Promise<Yatra | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getYatraBySlug(arg0);
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYatraBySlug(arg0);
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementBlogViews(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementBlogViews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementBlogViews(arg0);
            return result;
        }
    }
    async initAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initAdmin();
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initAdmin();
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinWaitlist(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<WaitlistResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinWaitlist(arg0, arg1, arg2, arg3, arg4);
                return from_candid_WaitlistResult_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinWaitlist(arg0, arg1, arg2, arg3, arg4);
            return from_candid_WaitlistResult_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async notifyNextOnWaitlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.notifyNextOnWaitlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.notifyNextOnWaitlist(arg0);
            return result;
        }
    }
    async promoteFromWaitlist(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteFromWaitlist(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteFromWaitlist(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWishlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async sendManualWaitlistNotification(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendManualWaitlistNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendManualWaitlistNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async setStripeSecretKey(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeSecretKey(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeSecretKey(arg0, arg1);
            return result;
        }
    }
    async submitCorporateLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<CorporateLead> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCorporateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCorporateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async submitReview(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: string): Promise<ReviewPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async subscribe(arg0: string, arg1: Array<NewsletterPreference>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribe(arg0, to_candid_vec_n71(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribe(arg0, to_candid_vec_n71(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async unsubscribe(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unsubscribe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsubscribe(arg0);
            return result;
        }
    }
    async updateAnnouncement(arg0: string, arg1: string, arg2: boolean): Promise<{
        __kind__: "ok";
        ok: AnnouncementPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2);
                return from_candid_variant_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2);
            return from_candid_variant_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBatch(arg0: bigint, arg1: BatchUpdateInput): Promise<{
        __kind__: "ok";
        ok: BatchPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatch(arg0, to_candid_BatchUpdateInput_n75(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatch(arg0, to_candid_BatchUpdateInput_n75(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGuideAvailability(arg0: string, arg1: GuideAvailability): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuideAvailability(arg0, to_candid_GuideAvailability_n77(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuideAvailability(arg0, to_candid_GuideAvailability_n77(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGuidePhoto(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuidePhoto(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuidePhoto(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: PaymentStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n79(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n79(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertGuide(arg0: GuidePublic): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertGuide(to_candid_GuidePublic_n81(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertGuide(to_candid_GuidePublic_n81(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async voteFaq(arg0: string, arg1: bigint, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.voteFaq(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteFaq(arg0, arg1, arg2);
            return result;
        }
    }
    async voteHelpful(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.voteHelpful(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteHelpful(arg0);
            return result;
        }
    }
}
function from_candid_BatchPublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchPublic): BatchPublic {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BatchStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchStatus): BatchStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_BlogCategory_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogCategory): BlogCategory {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_BlogPostPublic_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPostPublic): BlogPostPublic {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_BookingPublic_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingPublic): BookingPublic {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_GuideAvailability_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuideAvailability): GuideAvailability {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_GuidePublic_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuidePublic): GuidePublic {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_LoyaltyTier_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoyaltyTier): LoyaltyTier {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_MealPreference_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealPreference): MealPreference {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_TravelerInfo_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TravelerInfo): TravelerInfo {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Trek_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trek): Trek {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_WaitlistEntryPublic_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaitlistEntryPublic): WaitlistEntryPublic {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_WaitlistResult_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaitlistResult): WaitlistResult {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_WaitlistStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaitlistStatus): WaitlistStatus {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BatchAvailability]): BatchAvailability | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BatchPublic]): BatchPublic | null {
    return value.length === 0 ? null : from_candid_BatchPublic_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPostPublic]): BlogPostPublic | null {
    return value.length === 0 ? null : from_candid_BlogPostPublic_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingPublic]): BookingPublic | null {
    return value.length === 0 ? null : from_candid_BookingPublic_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GuidePublic]): GuidePublic | null {
    return value.length === 0 ? null : from_candid_GuidePublic_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trek]): Trek | null {
    return value.length === 0 ? null : from_candid_Trek_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Yatra]): Yatra | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    mealPreference: _MealPreference;
    name: string;
    medicalConditions: string;
    emergencyContact: string;
    gender: string;
    tshirtSize: string;
}): {
    age: bigint;
    mealPreference: MealPreference;
    name: string;
    medicalConditions: string;
    emergencyContact: string;
    gender: string;
    tshirtSize: string;
} {
    return {
        age: value.age,
        mealPreference: from_candid_MealPreference_n11(_uploadFile, _downloadFile, value.mealPreference),
        name: value.name,
        medicalConditions: value.medicalConditions,
        emergencyContact: value.emergencyContact,
        gender: value.gender,
        tshirtSize: value.tshirtSize
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BatchStatus;
    endDate: string;
    guideId: string;
    pricePerPerson: bigint;
    totalSeats: bigint;
    bookedSeats: bigint;
    isSoldOut: boolean;
    trekSlug: _Slug;
    seatsAvailable: bigint;
    startDate: string;
}): {
    id: bigint;
    status: BatchStatus;
    endDate: string;
    guideId: string;
    pricePerPerson: bigint;
    totalSeats: bigint;
    bookedSeats: bigint;
    isSoldOut: boolean;
    trekSlug: Slug;
    seatsAvailable: bigint;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_BatchStatus_n19(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        guideId: value.guideId,
        pricePerPerson: value.pricePerPerson,
        totalSeats: value.totalSeats,
        bookedSeats: value.bookedSeats,
        isSoldOut: value.isSoldOut,
        trekSlug: value.trekSlug,
        seatsAvailable: value.seatsAvailable,
        startDate: value.startDate
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    referralCode: string;
    city: string;
    name: string;
    createdAt: _Timestamp;
    email: string;
    phone: string;
    wishlist: Array<_Slug>;
    referralCredits: bigint;
    loyaltyTier: _LoyaltyTier;
    totalTreksCompleted: bigint;
}): {
    principal: UserId;
    referralCode: string;
    city: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    phone: string;
    wishlist: Array<Slug>;
    referralCredits: bigint;
    loyaltyTier: LoyaltyTier;
    totalTreksCompleted: bigint;
} {
    return {
        principal: value.principal,
        referralCode: value.referralCode,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        phone: value.phone,
        wishlist: value.wishlist,
        referralCredits: value.referralCredits,
        loyaltyTier: from_candid_LoyaltyTier_n29(_uploadFile, _downloadFile, value.loyaltyTier),
        totalTreksCompleted: value.totalTreksCompleted
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    currentAssignment: [] | [string];
    yearsExperience: bigint;
    name: string;
    designation: string;
    favoriteTrek: string;
    availability: _GuideAvailability;
    rating: number;
    photo: string;
    certifications: Array<string>;
    totalTreksLed: bigint;
}): {
    id: string;
    bio: string;
    currentAssignment?: string;
    yearsExperience: bigint;
    name: string;
    designation: string;
    favoriteTrek: string;
    availability: GuideAvailability;
    rating: number;
    photo: string;
    certifications: Array<string>;
    totalTreksLed: bigint;
} {
    return {
        id: value.id,
        bio: value.bio,
        currentAssignment: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.currentAssignment)),
        yearsExperience: value.yearsExperience,
        name: value.name,
        designation: value.designation,
        favoriteTrek: value.favoriteTrek,
        availability: from_candid_GuideAvailability_n36(_uploadFile, _downloadFile, value.availability),
        rating: value.rating,
        photo: value.photo,
        certifications: value.certifications,
        totalTreksLed: value.totalTreksLed
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: string;
    durationDays: bigint;
    startingPoint: string;
    tagline: string;
    durationNights: bigint;
    difficulty: _Difficulty;
    name: string;
    bestTime: string;
    slug: _Slug;
    heroImage: string;
    nearestAirport: string;
    trekDistance: bigint;
    shortDescription: string;
    isFeatured: boolean;
    maxAltitude: bigint;
    basePrice: bigint;
    nearestRailhead: string;
}): {
    id: bigint;
    region: string;
    durationDays: bigint;
    startingPoint: string;
    tagline: string;
    durationNights: bigint;
    difficulty: Difficulty;
    name: string;
    bestTime: string;
    slug: Slug;
    heroImage: string;
    nearestAirport: string;
    trekDistance: bigint;
    shortDescription: string;
    isFeatured: boolean;
    maxAltitude: bigint;
    basePrice: bigint;
    nearestRailhead: string;
} {
    return {
        id: value.id,
        region: value.region,
        durationDays: value.durationDays,
        startingPoint: value.startingPoint,
        tagline: value.tagline,
        durationNights: value.durationNights,
        difficulty: from_candid_Difficulty_n41(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        bestTime: value.bestTime,
        slug: value.slug,
        heroImage: value.heroImage,
        nearestAirport: value.nearestAirport,
        trekDistance: value.trekDistance,
        shortDescription: value.shortDescription,
        isFeatured: value.isFeatured,
        maxAltitude: value.maxAltitude,
        basePrice: value.basePrice,
        nearestRailhead: value.nearestRailhead
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentStatus: _PaymentStatus;
    userId: _UserId;
    createdAt: _Timestamp;
    travelers: Array<_TravelerInfo>;
    totalAmount: bigint;
    addOns: Array<_AddOn>;
    trekSlug: _Slug;
    batchId: bigint;
    stripeSessionId: [] | [string];
}): {
    id: bigint;
    paymentStatus: PaymentStatus;
    userId: UserId;
    createdAt: Timestamp;
    travelers: Array<TravelerInfo>;
    totalAmount: bigint;
    addOns: Array<AddOn>;
    trekSlug: Slug;
    batchId: bigint;
    stripeSessionId?: string;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n6(_uploadFile, _downloadFile, value.paymentStatus),
        userId: value.userId,
        createdAt: value.createdAt,
        travelers: from_candid_vec_n8(_uploadFile, _downloadFile, value.travelers),
        totalAmount: value.totalAmount,
        addOns: value.addOns,
        trekSlug: value.trekSlug,
        batchId: value.batchId,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.stripeSessionId))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    views: bigint;
    slug: _Slug;
    tags: Array<string>;
    publishedAt: _Timestamp;
    author: string;
    readTime: bigint;
    heroImage: string;
    excerpt: string;
    category: _BlogCategory;
}): {
    id: bigint;
    title: string;
    content: string;
    views: bigint;
    slug: Slug;
    tags: Array<string>;
    publishedAt: Timestamp;
    author: string;
    readTime: bigint;
    heroImage: string;
    excerpt: string;
    category: BlogCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        views: value.views,
        slug: value.slug,
        tags: value.tags,
        publishedAt: value.publishedAt,
        author: value.author,
        readTime: value.readTime,
        heroImage: value.heroImage,
        excerpt: value.excerpt,
        category: from_candid_BlogCategory_n51(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WaitlistStatus;
    name: string;
    createdAt: bigint;
    email: string;
    notifiedAt: [] | [bigint];
    batchId: string;
    phone: string;
    position: bigint;
    numPeople: bigint;
}): {
    id: string;
    status: WaitlistStatus;
    name: string;
    createdAt: bigint;
    email: string;
    notifiedAt?: bigint;
    batchId: string;
    phone: string;
    position: bigint;
    numPeople: bigint;
} {
    return {
        id: value.id,
        status: from_candid_WaitlistStatus_n64(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        notifiedAt: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.notifiedAt)),
        batchId: value.batchId,
        phone: value.phone,
        position: value.position,
        numPeople: value.numPeople
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Veg: null;
} | {
    NonVeg: null;
}): MealPreference {
    return "Veg" in value ? MealPreference.Veg : "NonVeg" in value ? MealPreference.NonVeg : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BatchPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BatchPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BatchPublic_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Full: null;
} | {
    Open: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
}): BatchStatus {
    return "Full" in value ? BatchStatus.Full : "Open" in value ? BatchStatus.Open : "Cancelled" in value ? BatchStatus.Cancelled : "Completed" in value ? BatchStatus.Completed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        bookingId: bigint;
        checkoutUrl: string;
        sessionId: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        bookingId: bigint;
        checkoutUrl: string;
        sessionId: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BookingPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BookingPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BookingPublic_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SummitMaster: null;
} | {
    Explorer: null;
} | {
    Trailblazer: null;
}): LoyaltyTier {
    return "SummitMaster" in value ? LoyaltyTier.SummitMaster : "Explorer" in value ? LoyaltyTier.Explorer : "Trailblazer" in value ? LoyaltyTier.Trailblazer : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    OnTrek: null;
} | {
    OnLeave: null;
}): GuideAvailability {
    return "Available" in value ? GuideAvailability.Available : "OnTrek" in value ? GuideAvailability.OnTrek : "OnLeave" in value ? GuideAvailability.OnLeave : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Easy: null;
} | {
    Extreme: null;
} | {
    Difficult: null;
} | {
    Moderate: null;
}): Difficulty {
    return "Easy" in value ? Difficulty.Easy : "Extreme" in value ? Difficulty.Extreme : "Difficult" in value ? Difficulty.Difficult : "Moderate" in value ? Difficulty.Moderate : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Stories: null;
} | {
    Gear: null;
} | {
    TrekTips: null;
} | {
    YatraGuides: null;
}): BlogCategory {
    return "Stories" in value ? BlogCategory.Stories : "Gear" in value ? BlogCategory.Gear : "TrekTips" in value ? BlogCategory.TrekTips : "YatraGuides" in value ? BlogCategory.YatraGuides : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Notified: null;
} | {
    Booked: null;
} | {
    Waiting: null;
} | {
    Expired: null;
}): WaitlistStatus {
    return "Notified" in value ? WaitlistStatus.Notified : "Booked" in value ? WaitlistStatus.Booked : "Waiting" in value ? WaitlistStatus.Waiting : "Expired" in value ? WaitlistStatus.Expired : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): PaymentStatus {
    return "Paid" in value ? PaymentStatus.Paid : "Cancelled" in value ? PaymentStatus.Cancelled : "Pending" in value ? PaymentStatus.Pending : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        waitlistId: string;
        position: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        waitlistId: string;
        position: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AnnouncementPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AnnouncementPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GuidePublic>): Array<GuidePublic> {
    return value.map((x)=>from_candid_GuidePublic_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trek>): Array<Trek> {
    return value.map((x)=>from_candid_Trek_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BatchPublic>): Array<BatchPublic> {
    return value.map((x)=>from_candid_BatchPublic_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPostPublic>): Array<BlogPostPublic> {
    return value.map((x)=>from_candid_BlogPostPublic_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingPublic>): Array<BookingPublic> {
    return value.map((x)=>from_candid_BookingPublic_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WaitlistEntryPublic>): Array<WaitlistEntryPublic> {
    return value.map((x)=>from_candid_WaitlistEntryPublic_n62(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TravelerInfo>): Array<TravelerInfo> {
    return value.map((x)=>from_candid_TravelerInfo_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BatchCreateInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchCreateInput): _BatchCreateInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_BatchUpdateInput_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchUpdateInput): _BatchUpdateInput {
    return to_candid_record_n76(_uploadFile, _downloadFile, value);
}
function to_candid_BlogCategory_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): _BlogCategory {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_GuideAvailability_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideAvailability): _GuideAvailability {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_GuidePublic_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuidePublic): _GuidePublic {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_MealPreference_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealPreference): _MealPreference {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_NewsletterPreference_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsletterPreference): _NewsletterPreference {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_TravelerInfo_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TravelerInfo): _TravelerInfo {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    maxSeats: bigint;
    endDate: string;
    meetingPoint: string;
    guideId?: string;
    pricePerPerson: bigint;
    guideName?: string;
    trekName: string;
    trekSlug: string;
    startDate: string;
}): {
    status: string;
    maxSeats: bigint;
    endDate: string;
    meetingPoint: string;
    guideId: [] | [string];
    pricePerPerson: bigint;
    guideName: [] | [string];
    trekName: string;
    trekSlug: string;
    startDate: string;
} {
    return {
        status: value.status,
        maxSeats: value.maxSeats,
        endDate: value.endDate,
        meetingPoint: value.meetingPoint,
        guideId: value.guideId ? candid_some(value.guideId) : candid_none(),
        pricePerPerson: value.pricePerPerson,
        guideName: value.guideName ? candid_some(value.guideName) : candid_none(),
        trekName: value.trekName,
        trekSlug: value.trekSlug,
        startDate: value.startDate
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    mealPreference: MealPreference;
    name: string;
    medicalConditions: string;
    emergencyContact: string;
    gender: string;
    tshirtSize: string;
}): {
    age: bigint;
    mealPreference: _MealPreference;
    name: string;
    medicalConditions: string;
    emergencyContact: string;
    gender: string;
    tshirtSize: string;
} {
    return {
        age: value.age,
        mealPreference: to_candid_MealPreference_n24(_uploadFile, _downloadFile, value.mealPreference),
        name: value.name,
        medicalConditions: value.medicalConditions,
        emergencyContact: value.emergencyContact,
        gender: value.gender,
        tshirtSize: value.tshirtSize
    };
}
function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: string;
    maxSeats?: bigint;
    endDate?: string;
    meetingPoint?: string;
    guideId?: string;
    pricePerPerson?: bigint;
    guideName?: string;
    trekName?: string;
    trekSlug?: string;
    startDate?: string;
}): {
    status: [] | [string];
    maxSeats: [] | [bigint];
    endDate: [] | [string];
    meetingPoint: [] | [string];
    guideId: [] | [string];
    pricePerPerson: [] | [bigint];
    guideName: [] | [string];
    trekName: [] | [string];
    trekSlug: [] | [string];
    startDate: [] | [string];
} {
    return {
        status: value.status ? candid_some(value.status) : candid_none(),
        maxSeats: value.maxSeats ? candid_some(value.maxSeats) : candid_none(),
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        meetingPoint: value.meetingPoint ? candid_some(value.meetingPoint) : candid_none(),
        guideId: value.guideId ? candid_some(value.guideId) : candid_none(),
        pricePerPerson: value.pricePerPerson ? candid_some(value.pricePerPerson) : candid_none(),
        guideName: value.guideName ? candid_some(value.guideName) : candid_none(),
        trekName: value.trekName ? candid_some(value.trekName) : candid_none(),
        trekSlug: value.trekSlug ? candid_some(value.trekSlug) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    currentAssignment?: string;
    yearsExperience: bigint;
    name: string;
    designation: string;
    favoriteTrek: string;
    availability: GuideAvailability;
    rating: number;
    photo: string;
    certifications: Array<string>;
    totalTreksLed: bigint;
}): {
    id: string;
    bio: string;
    currentAssignment: [] | [string];
    yearsExperience: bigint;
    name: string;
    designation: string;
    favoriteTrek: string;
    availability: _GuideAvailability;
    rating: number;
    photo: string;
    certifications: Array<string>;
    totalTreksLed: bigint;
} {
    return {
        id: value.id,
        bio: value.bio,
        currentAssignment: value.currentAssignment ? candid_some(value.currentAssignment) : candid_none(),
        yearsExperience: value.yearsExperience,
        name: value.name,
        designation: value.designation,
        favoriteTrek: value.favoriteTrek,
        availability: to_candid_GuideAvailability_n77(_uploadFile, _downloadFile, value.availability),
        rating: value.rating,
        photo: value.photo,
        certifications: value.certifications,
        totalTreksLed: value.totalTreksLed
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealPreference): {
    Veg: null;
} | {
    NonVeg: null;
} {
    return value == MealPreference.Veg ? {
        Veg: null
    } : value == MealPreference.NonVeg ? {
        NonVeg: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): {
    Stories: null;
} | {
    Gear: null;
} | {
    TrekTips: null;
} | {
    YatraGuides: null;
} {
    return value == BlogCategory.Stories ? {
        Stories: null
    } : value == BlogCategory.Gear ? {
        Gear: null
    } : value == BlogCategory.TrekTips ? {
        TrekTips: null
    } : value == BlogCategory.YatraGuides ? {
        YatraGuides: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Easy: null;
} | {
    Extreme: null;
} | {
    Difficult: null;
} | {
    Moderate: null;
} {
    return value == Difficulty.Easy ? {
        Easy: null
    } : value == Difficulty.Extreme ? {
        Extreme: null
    } : value == Difficulty.Difficult ? {
        Difficult: null
    } : value == Difficulty.Moderate ? {
        Moderate: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsletterPreference): {
    BlogPosts: null;
} | {
    Offers: null;
} | {
    WeatherAlerts: null;
} | {
    NewBatches: null;
} {
    return value == NewsletterPreference.BlogPosts ? {
        BlogPosts: null
    } : value == NewsletterPreference.Offers ? {
        Offers: null
    } : value == NewsletterPreference.WeatherAlerts ? {
        WeatherAlerts: null
    } : value == NewsletterPreference.NewBatches ? {
        NewBatches: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideAvailability): {
    Available: null;
} | {
    OnTrek: null;
} | {
    OnLeave: null;
} {
    return value == GuideAvailability.Available ? {
        Available: null
    } : value == GuideAvailability.OnTrek ? {
        OnTrek: null
    } : value == GuideAvailability.OnLeave ? {
        OnLeave: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    Paid: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
} {
    return value == PaymentStatus.Paid ? {
        Paid: null
    } : value == PaymentStatus.Cancelled ? {
        Cancelled: null
    } : value == PaymentStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TravelerInfo>): Array<_TravelerInfo> {
    return value.map((x)=>to_candid_TravelerInfo_n22(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<NewsletterPreference>): Array<_NewsletterPreference> {
    return value.map((x)=>to_candid_NewsletterPreference_n72(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
